filter:
    excluded_paths:
        - 'tests/*'
        - 'scripts/*'
        - 'build/*'
        - 'example/*'

checks:
    php:
        classes_in_camel_caps: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        avoid_todo_comments: true
        avoid_fixme_comments: true
        avoid_multiple_statements_on_same_line: true
        avoid_perl_style_comments: true
        fix_line_ending: true
        encourage_postdec_operator: true
        encourage_single_quotes: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: true
            order_alphabetically: true
        function_in_camel_caps: true
        line_length:
            max_length: '150'
        no_goto: true
        no_long_variable_names:
            maximum: '20'
        no_short_method_names:
            minimum: '3'
        parameters_in_camelcaps: true
        properties_in_camelcaps: true
        return_doc_comment_if_not_inferrable: true
        return_doc_comments: true
        simplify_boolean_return: true
        use_self_instead_of_fqcn: true

coding_style:
    php:
        spaces:
            before_parentheses:
                closure_definition: true
            other:
                after_type_cast: false
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

tools:
    external_code_coverage: true

    php_code_sniffer:
        config:
            standard: "PSR2"
