language: php

php: '7.1'

before_install:
  - scripts/install

install:
  - composer install
  - cp phpunit.xml.dist phpunit.xml

before_script:
  - scripts/harness &

script: |
         ./vendor/bin/phpunit \
           --coverage-clover=build/coverage.clover

after_script:
  - ./scripts/ocular code-coverage:upload --format=php-clover build/coverage.clover
  - pkill -f scripts/harness

cache:
  directories:
    - build/cache

addons:
  apt:
    packages:
      - build-essential
      - tcl8.5
