language: php

php: '7.1'

before_install:
  - scripts/install

install:
  - composer install
  - cp phpunit.xml.dist phpunit.xml

before_script:
  - scripts/harness

addons:
  apt:
    packages:
      - build-essential
      - tcl8.5

cache:
  directories:
    - build/cache
