language: php

php: '7.1'

before_install:
  - scripts/install

install:
  - composer install
  - cp phpunit.xml.dist phpunit.xml

before_script:
  - scripts/harness &

after_script:
  - pkill -f scripts/harness

cache:
  directories:
    - build/cache
