#!/bin/bash
# Bash functions

set -ex

export DISQUE_BUILD_CACHE_DIR=${DISQUE_BUILD_CACHE_DIR:-build/cache}
export DISQUE_SERVER_VERSION=${DISQUE_SERVER_VERSION:-'1.0-rc1'}
export DISQUE_SOURCE_URL=https://github.com/antirez/disque/archive/${DISQUE_SERVER_VERSION}.tar.gz
export DISQUE_SOURCE_DOWNLOAD=${DISQUE_BUILD_CACHE_DIR}/disque-${DISQUE_SERVER_VERSION}.tar.gz
export DISQUE_SOURCE_DIR="${DISQUE_BUILD_CACHE_DIR}/disque-${DISQUE_SERVER_VERSION}"

export DISQUE_SOURCE_INSTALL_PREFIX=/usr/local/bin
export DISQUE_SOURCE_INSTALL_ROOT=1
export DISQUE_SOURCE_INSTALL=1

if [[ ${TRAVIS} == "true" ]]; then
    # Always use the source version, don't bother installing
    export DISQUE_SOURCE_INSTALL=0
    export DISQUE=${DISQUE:-"${DISQUE_SOURCE_DIR}/src/disque"}
    export DISQUE_SERVER=${DISQUE_SERVER:-"${DISQUE_SOURCE_DIR}/src/disque-server"}
else
    export DISQUE=${DISQUE:-'disque'}
    export DISQUE_SERVER=${DISQUE_SERVER:-'disque-server'}
fi

env | grep DISQUE

mkdir -p ${DISQUE_BUILD_CACHE_DIR}

function installPackage() {
    export DEBIAN_FRONTEND=noninteractive

    if [[ $EUID -ne 0 ]]; then
        sudo apt-get install -y "$@"
    else
        apt-get install -y "$@"
    fi
}

function installFromSource() {
    set -x
    echo "Installing disque from source"
    mkdir -p $(dirname $DISQUE_SOURCE_DIR)

    if [[ ! -f $DISQUE_SOURCE_DOWNLOAD ]]; then
        echo "Downloading disque source from $DISQUE_SOURCE_URL"
        wget ${DISQUE_SOURCE_URL} -O ${DISQUE_SOURCE_DOWNLOAD}
    fi

    if [[ ! -d ${DISQUE_SOURCE_DIR} ]]; then
        echo "Extracting Disque source from $DISQUE_SOURCE_DOWNLOAD"
        tar zvxf ${DISQUE_SOURCE_DOWNLOAD} -C $(dirname ${DISQUE_SOURCE_DIR})
    fi

    if [[ ! -x "$DISQUE_SOURCE_DIR/src/disque" ]]; then
        echo "Running make"
        pushd ${DISQUE_SOURCE_DIR}
        make distclean
#        pushd deps
#        make hiredis jemalloc linenoise
#        popd
        make
        popd
    fi

    if [[ ${DISQUE_SOURCE_INSTALL} -eq 1 && ! -x ${DISQUE_SOURCE_INSTALL_PREFIX}/bin/disque ]]; then
        echo "Running make install"
        pushd ${DISQUE_SOURCE_DIR}

        if [[ $EUID -ne 0 ]]; then
            if [[ ${DISQUE_SOURCE_INSTALL_ROOT} -ne 1 ]]; then
                PREFIX=${DISQUE_SOURCE_INSTALL_PREFIX} make install
            else
                PREFIX=${DISQUE_SOURCE_INSTALL_PREFIX} sudo -E make install
            fi
        else
            make install
        fi

        popd
    fi
}
