#!/bin/bash
# Bash functions

readonly CACHE_DIR=${WERCKER_CACHE_DIR:-build}

readonly DISQUE_SERVER_VERSION="1.0-rc1"
readonly DISQUE_SOURCE_URL=https://github.com/antirez/disque/archive/${DISQUE_SERVER_VERSION}.tar.gz
readonly DISQUE_SOURCE_DOWNLOAD=${CACHE_DIR}/disque-${DISQUE_SERVER_VERSION}.tar.gz
readonly DISQUE_SOURCE_DIR=${CACHE_DIR}/disque-${DISQUE_SERVER_VERSION}

DISQUE_SOURCE_INSTALL_PREFIX=/usr/local/bin
DISQUE_SOURCE_INSTALL_ROOT=1
DISQUE=${DISQUE:-'disque'}
DISQUE_SERVER=${DISQUE_SERVER:-'disque-server'}

if [[ ${TRAVIS} == "true" ]]; then
    mkdir -p /home/travis/opt/
    DISQUE_SOURCE_INSTALL_PREFIX=/home/travis/opt
    DISQUE_SOURCE_INSTALL_ROOT=0
    DISQUE=${DISQUE:-"${DISQUE_SOURCE_INSTALL_PREFIX}/bin/disque"}
    DISQUE_SERVER=${DISQUE_SERVER:-"${DISQUE_SOURCE_INSTALL_PREFIX}/bin/disque-server"}
fi

function installPackage() {
    export DEBIAN_FRONTEND=noninteractive

    if [[ $EUID -ne 0 ]]; then
        sudo apt-get install -y "$@"
    else
        apt-get install -y "$@"
    fi
}

function installFromSource() {
    set -x

    mkdir -p $(dirname $DISQUE_SOURCE_DIR)

    if [[ ! -f $DISQUE_SOURCE_DOWNLOAD ]]; then
        echo "Downloading disque source from $DISQUE_SOURCE_URL"
        wget ${DISQUE_SOURCE_URL} -O ${DISQUE_SOURCE_DOWNLOAD}
    fi

    if [[ ! -d ${DISQUE_SOURCE_DIR} ]]; then
        echo "Extracting Disque source from $DISQUE_SOURCE_DOWNLOAD"
        tar zvxf ${DISQUE_SOURCE_DOWNLOAD} -C $(dirname ${DISQUE_SOURCE_DIR})
    fi

    if [[ ! -x "$DISQUE_SOURCE_DIR/src/disque" ]]; then
        echo "Running make"
        pushd ${DISQUE_SOURCE_DIR}
        make distclean
#        pushd deps
#        make hiredis jemalloc linenoise
#        popd
        make
        popd
    fi

    if [[ ! -x ${DISQUE_SOURCE_INSTALL_PREFIX}/bin/disque ]]; then
        echo "Running make install"
        pushd ${DISQUE_SOURCE_DIR}

        if [[ $EUID -ne 0 ]]; then
            if [[ ${DISQUE_SOURCE_INSTALL_ROOT} -ne 1 ]]; then
                PREFIX=${DISQUE_SOURCE_INSTALL_PREFIX} make install
            else
                PREFIX=${DISQUE_SOURCE_INSTALL_PREFIX} sudo -E make install
            fi
        else
            make install
        fi

        popd
    fi
}
