#!/bin/bash

set -ex

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source ${DIR}/_common

set +e
hash disque > /dev/null 2>&1
pathDisque=$?
set -e

if [[ ( ${DISQUE} == "disque" && ${pathDisque} -ne 0 ) || ( ${DISQUE} != "disque" && ! -x ${DISQUE} ) ]]; then
    if [[ "$OSTYPE" == "linux-gnu" ]]; then
        if [[ $(lsb_release -si) == "Ubuntu" ]]; then
            if dpkg --compare-versions $(lsb_release -rs) 'ge' '16.04'; then
                installPackage disque
            else
                installFromSource
            fi
        else
            installFromSource
        fi
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        brew tap colstrom/homebrew-disque
        brew install colstrom/homebrew-disque/disque
    fi
fi

if [[ ${DISQUE} == "disque" ]]; then
    if ! hash disque > /dev/null 2>&1; then
        echo "Could not find disque on PATH after install" >&2
        exit 2
    fi
else
    if [[ ! -x ${DISQUE} ]]; then
        echo "Could not find disque at $DISQUE" >&2
        exit 2
    fi
fi
